[package]
name = "auto-lsp"
authors = ["Clauzel Adrien"]
license = "MIT"
repository = "https://github.com/adclz/auto-lsp"
description = """
A rust crate for creating AST and LSP servers powered by tree-sitter queries.
"""
categories = ["parsing"]
keywords = ["parser", "tree-sitter", "lsp"]
version = "0.2.0"
edition = "2021"
readme = "README.MD"

[dependencies]
auto-lsp-core = { path = "./core", version = "0.2.0" }
auto-lsp-macros = { path = "./proc-macros", version = "0.1.1" }
phf = { version = "0.11", features = ["macros"] }
tree-sitter = "0.24.6"
tree-sitter-language = "0.1.3"
lsp-types = "0.94.1"
downcast-rs = "1.2.1"
constcat = "0.5.1"
streaming-iterator = "0.1.9"
regex = "1.11.1"
anyhow = "1.0.91"
parking_lot = "0.12.3"
stderrlog = "0.6.0"
log = "0.4.22"
thiserror = "2.0.11"
miette = { version = "7.4.0", features = ["fancy"] }
lsp-server = { version = "0.7.6", optional = true }
serde = { version = "1.0.189", optional = true }
serde_json = { version = "1.0.107", optional = true }
walkdir = { version = "2", optional = true }
crossbeam-channel = { version = "0.5.13", optional = true }
texter = { version = "0.1.2", optional = true }
rayon = { version = "1.10", optional = true }
tree-sitter-python = { version = "0.23.6", optional = true }
tree-sitter-html = { version = "0.23.2", optional = true }

[workspace]
members = ["core", "proc-macros"]
exclude = ["extensions/vscode-python-wasi-lsp/server"]

[workspace.dependencies]
lsp-types = "0.94.1"
tree-sitter = "0.24.3"
downcast-rs = "1.2.1"
constcat = "0.5.1"
streaming-iterator = "0.1.9"
parking_lot = "0.12.3"
log = "0.4.22"
texter = "0.1.2"
rayon = "1.10"
anyhow = "1.0.91"
regex = "1.11.1"
thiserror = "2.0.11"
miette = "7.4.0"

[features]
default = []
deadlock_detection = ["parking_lot/nightly", "parking_lot/deadlock_detection"]
log = ["auto-lsp-core/log"]
lsp_server = [
    "dep:serde",
    "dep:serde_json",
    "dep:walkdir",
    "dep:lsp-server",
    "dep:crossbeam-channel",
    "dep:texter",
]
rayon = ["auto-lsp-core/rayon", "dep:rayon"]
wasm = ["parking_lot/nightly"]
python = ["lsp_server", "dep:tree-sitter-python"]
html = ["lsp_server", "dep:tree-sitter-html"]

[package.metadata.docs.rs]
all-features = true

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
lsp-server = "0.7.6"
serde = "1.0.189"
serde_json = "1.0.107"
walkdir = "2"
crossbeam-channel = "0.5.13"
texter = "0.1.2"
rayon = "1.10"
tree-sitter-python = "0.23.6"
tree-sitter-html = "0.23.2"
rstest = "0.24.0"
tempfile = "3.15.0"
static_assertions = "1.1.0"
impls = "1.0.3"

[[bench]]
name = "main"
harness = false
required-features = ["python"]
