[package]
name = "auto-lsp"
authors = ["Clauzel Adrien"]
license = "GPL-3.0"
repository = "https://github.com/adclz/auto-lsp"
description = """
A rust crate for creating AST and LSP servers powered by tree-sitter queries.
"""
categories = ["parsing"]
keywords = ["parser", "tree-sitter", "lsp"]
version = "0.5.1"
edition = "2021"
readme = "README.MD"

[dependencies]
auto-lsp-core = { path = "./crates/core", version = "0.5.0" }
tree-sitter = "0.24.7"
tree-sitter-language = "0.1.5"
lsp-types = "0.94.1"
streaming-iterator = "0.1.9"
regex = "1.11.1"
anyhow = "1.0.97"
parking_lot = "0.12.3"
log = "0.4.26"
salsa = "0.19.0"
rayon = "1.10"
rayon-par-bridge = "0.1.0"
texter = { version = "0.1.5", default-features = false }
lsp-server = { version = "0.7.8", optional = true }
serde = { version = "1.0.219", optional = true }
serde_json = { version = "1.0.140", optional = true }
walkdir = { version = "2.5.0", optional = true }
crossbeam-channel = { version = "0.5.14", optional = true }

[workspace]
members = ["crates/core"]
exclude = [
    "examples/vscode-wasi/server",
    "examples/vscode-native/server",
    "examples/native",
    "examples/ast-python",
    "examples/ast-html",
    "crates/codegen",
]

[workspace.dependencies]
texter = { version = "0.1.5", default-features = false }
lsp-types = "0.94.1"
tree-sitter = "0.24.7"
downcast-rs = "2.0.1"
streaming-iterator = "0.1.9"
parking_lot = "0.12.3"
log = "0.4.22"
rayon = "1.10"
anyhow = "1.0.97"
regex = "1.11.1"
tree-sitter-html = "0.23.2"
rstest = "0.25.0"
salsa = "0.19.0"
dashmap = "6.1.0"
thiserror = "2.0.12"
ariadne = "0.5.1"

[features]
default = []
lsp_server = [
    "dep:serde",
    "dep:serde_json",
    "dep:walkdir",
    "dep:lsp-server",
    "dep:crossbeam-channel",
]
wasm = ["parking_lot/nightly", "auto-lsp-core/wasm"]

[package.metadata.docs.rs]
features = ["lsp_server"]

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.14.0", features = ["criterion", "flamegraph"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[dev-dependencies]
tempfile = "3.19.0"

[[bench]]
name = "flame_graph"
harness = false
required-features = ["python"]

[[bench]]
name = "django"
harness = false
required-features = ["python"]
