[package]
name = "auto-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
auto-lsp-core = { path = "./core" }
auto-lsp-macros = { path = "./proc-macros" }
phf = { version = "0.11", features = ["macros"] }
tree-sitter = "0.24.6"
tree-sitter-language = "0.1.3"
rayon = "1.10"
lsp-server = "0.7.6"
lsp-types = "0.94.1"
walkdir = "2"
serde = "1.0.189"
serde_json = "1.0.107"
downcast-rs = "1.2.1"
constcat = "0.5.1"
streaming-iterator = "0.1.9"
regex = "1.11.1"
anyhow = "1.0.91"
crossbeam-channel = "0.5.13"
parking_lot = "0.12.3"
stderrlog = "0.6.0"
log =  "0.4.22"
texter = "0.1.2"

[features]
log = []

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
tree-sitter-python = "0.23.6"
tree-sitter-html = "0.23.2"

[workspace]
members = [
    "core",
    "proc-macros"
]
exclude = ["extensions/vscode-python-wasi-lsp/server"]

[workspace.dependencies]
lsp-types = "0.94.1"
tree-sitter = "0.24.3"
downcast-rs = "1.2.1"
constcat = "0.5.1"
streaming-iterator = "0.1.9"
parking_lot = "0.12.3"
log = "0.4.22"
texter = "0.1.2"

[[bench]]
name = "main"
harness = false
