#[cfg(doc)]
use auto_lsp_core::workspace::Workspace;
use auto_lsp_core::workspace::{Queries, TreeSitter};

/// Create the parsers with any given language and queries.
///
/// This generates a static map named `PARSERS of parsers that can be used to parse source code in the workspace.
///
/// Every [`Workspace`] is linked to a parser, which is used to parse the source code and build both the CST and AST.
///
/// To determine which parser to use for a source code, the server will check the language ID against the keys in the `PARSERS` map generated by this macro
///
/// # Example
/// ```rust
/// # use auto_lsp::seq;
/// # use auto_lsp::configure_parsers;
/// # use auto_lsp::core::ast::*;
/// static CORE_QUERY: &'static str = "
/// (module) @module
/// (function_definition
///    name: (identifier) @function.name) @function
/// ";
///
/// static COMMENT_QUERY: &'static str = "
/// (comment) @comment
/// ";
/// #[seq(query_name = "module", kind(symbol()))]
/// struct Module {}
///
/// configure_parsers!(
///     "python" => {
///         language: tree_sitter_python::LANGUAGE,
///         node_types: tree_sitter_python::NODE_TYPES,
///         ast_root: Module,
///         core: CORE_QUERY,
///         comment: Some(COMMENT_QUERY),
///         fold: None,
///         highlights: None
///     }
/// );
/// ```
#[macro_export]
macro_rules! configure_parsers {
    ($($extension: expr => {
            language: $language: path,
            node_types: $node_types: path,
            ast_root: $root: ident,
            core: $core: path,
            comment: $comment: expr,
            fold: $fold: expr,
            highlights: $highlights: expr
        }),*) => {
        pub static PARSERS: std::sync::LazyLock<std::collections::HashMap<&str, $crate::core::workspace::Parsers>> =
            std::sync::LazyLock::new(|| {
                let mut map = std::collections::HashMap::new();
                map.insert(
                    $($extension, $crate::core::workspace::Parsers {
                        tree_sitter: $crate::configure::parsers::create_parser($language, $node_types, $core, $comment, $fold, $highlights),
                        ast_parser: |workspace: &mut $crate::core::workspace::Workspace, document: &$crate::core::document::Document, range: Option<std::ops::Range<usize>>| {
                            use $crate::core::build::InvokeStackBuilder;

                            Ok::<$crate::core::ast::DynSymbol, $crate::lsp_types::Diagnostic>(
                                $crate::core::ast::Symbol::new_and_check($root::create_symbol(workspace, document, range)?, workspace).to_dyn(),
                            )
                        },
                    }),*
                );
                map
            });
    };
}

#[doc(hidden)]
pub fn create_parser(
    language: tree_sitter_language::LanguageFn,
    node_types: &'static str,
    core: &'static str,
    comments: Option<&'static str>,
    fold: Option<&'static str>,
    highlights: Option<&'static str>,
) -> TreeSitter {
    let mut parser = tree_sitter::Parser::new();
    parser.set_language(&language.into()).unwrap();

    let language = tree_sitter::Language::new(language);

    let core = tree_sitter::Query::new(&language, core).unwrap();
    let comments = comments.map(|path| tree_sitter::Query::new(&language, path).unwrap());
    let fold = fold.map(|path| tree_sitter::Query::new(&language, path).unwrap());
    let highlights = highlights.map(|path| tree_sitter::Query::new(&language, path).unwrap());
    TreeSitter {
        parser: parking_lot::RwLock::new(parser),
        node_types,
        language,
        queries: Queries {
            comments,
            fold,
            highlights,
            core,
        },
    }
}
