[package]
name = "auto-lsp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-types = { workspace = true }
tree-sitter = { workspace = true }
downcast-rs = { workspace = true }
streaming-iterator = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }
texter = { workspace = true }
const-str = "0.3.1"
const_panic = "0.2.11"