[package]
name = "vscode-wasi-server"
version = "0.1.0"
edition = "2021"

[dependencies]
auto-lsp = { path = "../../../", features = [
    "lsp_server",
    "log",
    "wasm",
    "rayon",
    "python",
] }
tree-sitter-python = "0.23.6"
