[package]
name = "native-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
auto-lsp = { path = "../../", features = ["lsp_server", "log", "python"] }
assert_cmd = "2.0.16"
tokio = { version = "1.44.0", features = ["full"] }
escargot = "0.5.13"
serde_json = "1.0"
serde = "1.0"

[dev-dependencies]
rstest = "0.24.0"
