[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.24.3"
tree-sitter-iec61131-3-2 = { path = "../../parser-iec-61131-3-2" }
rayon = "1.10"
lsp-server = "0.7.6"
lsp-types = "0.94.1"
lsp-textdocument = "0.3.2"
walkdir = "2"
serde = "1.0.189"
serde_json = "1.0.107"
auto-lsp-macros = { path = "./auto-lsp-macros" }
auto-lsp = { path = "./auto-lsp" }
phf = { version = "0.11", features = ["macros"] }
downcast-rs = "1.2.1"
lazy_static = "1.5.0"
constcat = "0.5.1"
streaming-iterator = "0.1.9"
regex = "1.11.1"
anyhow = "1.0.91"

[workspace]
members = [
    "auto-lsp-macros",
    "auto-lsp"
]

[workspace.dependencies]
lsp-types = "0.94.1"
tree-sitter = "0.24.3"
lsp-textdocument = "0.3.2"
downcast-rs = "1.2.1"
constcat = "0.5.1"
streaming-iterator = "0.1.9"

