name: Generate AST - native
on: 
  push:
    paths-ignore:
      - "**.md"
      - "**.js"
      - "**.ts"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.js"
      - "**.ts"  

jobs:
  test:
    name: cargo test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: rustup toolchain install nightly
      - run: rustup default nightly
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: main crate
        run: cargo test --all-features --workspace
      - name: python ast
        working-directory: ./examples/ast-python
        run: cargo test
      - name: html ast
        working-directory: ./examples/ast-html
        run: cargo test  