[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
auto-lsp = { path = "../../../", features = ["log", "wasm", "python_test"] }
phf = { version = "0.11", features = ["macros"] }
tree-sitter-python = "0.23.6"
